import {
    AlarmClock,
    AlarmClockCheck,
    Armchair,
    AudioLines,
    AudioWaveform,
    Bell,
    Book,
    BookOpen,
    CalendarCheck,
    CalendarDays,
    CalendarPlus,
    CalendarRange,
    CalendarX,
    Camera,
    ClipboardCheck,
    ClipboardList,
    ClipboardPen,
    ClipboardPlus,
    ClipboardX,
    DoorClosed,
    DoorOpen,
    Flag,
    Hand,
    Handshake,
    Headphones,
    Laptop,
    Lectern,
    Megaphone,
    Mic,
    MicOff,
    Monitor,
    MonitorSpeaker,
    Notebook,
    Pen,
    Presentation,
    Projector,
    ScreenShare,
    Share,
    Speaker,
    Timer,
    Tv,
    User,
    UserCheck,
    UserCog,
    UserPlus,
    UserSearch,
    Users,
    UsersRound,
    Video,
    Webcam,
} from "lucide-react";

export const roleIconMap = {
    Mic: Mic,
    MicOff: MicOff,
    Speaker: Speaker,
    Headphones: Headphones,
    AudioLines: AudioLines,
    AudioWaveform: AudioWaveform,
    Monitor: Monitor,
    MonitorSpeaker: MonitorSpeaker,
    Camera: Camera,
    Video: Video,
    Webcam: Webcam,
    ScreenShare: ScreenShare,
    Laptop: Laptop,
    Tv: Tv,
    Projector: Projector,
    User: User,
    UserCheck: UserCheck,
    UserPlus: UserPlus,
    UserCog: UserCog,
    UserSearch: UserSearch,
    Users: Users,
    UsersRound: UsersRound,
    Handshake: Handshake,
    DoorOpen: DoorOpen,
    DoorClosed: DoorClosed,
    Book: Book,
    BookOpen: BookOpen,
    Lectern: Lectern,
    Timer: Timer,
    AlarmClock: AlarmClock,
    AlarmClockCheck: AlarmClockCheck,
    ClipboardCheck: ClipboardCheck,
    ClipboardList: ClipboardList,
    ClipboardPen: ClipboardPen,
    ClipboardPlus: ClipboardPlus,
    ClipboardX: ClipboardX,
    CalendarDays: CalendarDays,
    CalendarCheck: CalendarCheck,
    CalendarPlus: CalendarPlus,
    CalendarRange: CalendarRange,
    CalendarX: CalendarX,
    Share: Share,
    Presentation: Presentation,
    Megaphone: Megaphone,
    Armchair: Armchair,
    Flag: Flag,
    Notebook: Notebook,
    Pen: Pen,
    Bell: Bell,
    Hand: Hand,
} as const;
